name: build

on:
  push:
    branches:
      - '!master'
  pull_request:
    branches: [ master ]

jobs:
  build-test:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 13
      uses: actions/setup-java@v1
      with:
        java-version: 13
    - name: Gen cache key
      run: |
        md5sum project/build.properties project/plugins.sbt build.sbt > $GITHUB_WORKSPACE/.sbt_cache_key
        cat $GITHUB_WORKSPACE/.sbt_cache_key
    - name: Check cache
      uses: actions/cache@v2.1.1
      with:
        key: sbt-${{ hashFiles('**/.sbt_cache_key') }}
        path: |
          ~/.ivy2
          ~/.sbt
          ~/.cache/coursier
    - name: Unit tests
      run:
        sbt test
