name: build-website

on:
  push:
    branches:
      - master
    paths:
      - 'website/**'

jobs:
  build-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.79.1'

      - name: Build
        uses: actions/setup-node@v2
        with:
          node-version: '12'
        run: |
          cd website
          npm install
          hugo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/public
